##
# DevShop: DevMaster Server with Apache
#

---
- hosts: all
  user: root
  vars_files:
    - vars.vagrant.yml
  roles:
    - opendevshop.aegir-user
    - opendevshop.aegir-apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - opendevshop.devmaster
