 
name: devshop
version: 0.1
summary: 'Drupal DevOps Platform: Develop, Test, & Deploy any Drupal site.'
description: |
  DevShop automates Drupal hosting, testing, and deployment. 
  Submit a pull request, get a copy of your site. 
  Push your code, automatically deploy and test it.

parts:
  hello:
    plugin: cmake
    source: src

apps:
  devshop-robo:
    command: bin/robo up
